groupName: porkbun.ntb.dev

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: 4ntb/porkbun-webhook
  tag: v1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
