# .github/workflows/release-chart.yaml
name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: deploy
          token: ${{ secrets.HELM_REPO_PAT }}
        env:
          # Configuration for pushing to the external repository now goes here,
          # using the environment variables expected by the 'cr' tool.
          CR_OWNER: cfv
          CR_GIT_REPO: porkbun-webhook-helm-repo
          CR_TOKEN: ${{ secrets.HELM_REPO_PAT }}
